---
site_name: iot-backend
site_description: An Open-Source prototype for collecting, working with and displaying sensor data from MQTT enabled IoT devices.
repo_name: iot-backend
repo_url: https://code.curious.bio/curious.bio/iot-backend

nav:
  - Home: README.md

theme:
  logo: images/logos/iot-platform.svg
  language: en
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

plugins:
  - glightbox
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: >
  Copyright &copy; 2023 Curious Community Labs e. V.
