okhv = "OKH-LOSHv1.0"

name = "iot-backend"
function = "IoT backend for analyzing open lab resource consumption and machine status"
image = ""

version = "0.1"
repo = "https://code.curious.bio/curious.bio/iot-backend"
release = "https://code.curious.bio/curious.bio/iot-backend/releases"

license = "CERN-OHL-S-2.0"
licensor = "Curious Community Labs e. V."

readme = "/README.md"

documentation-language = "en"
technology-readiness-level = "OTRL-5"
documentation-readiness-level = "ODRL-3*"

[[software]]
release = "0.1"
installation-guide = "/README.md"
