# version: '3.2'
services:
  mosquitto:
    # https://hub.docker.com/_/eclipse-mosquitto
    image: eclipse-mosquitto:2.0
    restart: always
    container_name: mosquitto
    networks:
      - lauds_gw_network
    ports:
      - 1883:1883
    volumes:
      - ../mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    # https://hub.docker.com/_/influxdb
    image: influxdb:2.6
    restart: always
    container_name: influxdb
    networks:
      - lauds_gw_network
    ports:
      - 8086:8086
    volumes:
      - influxdb2:/var/lib/influxdb2

  grafana:
    # https://hub.docker.com/r/grafana/grafana
    image: grafana/grafana:9.3.6
    depends_on:
      - influxdb
    restart: always
    container_name: grafana
    networks:
      - lauds_gw_network
    ports:
      - 3000:3000
    volumes:
      - grafana-dashboards:/var/lib/grafana
      - grafana-data:/data/
      - ../dashboard/grafana.ini:/etc/grafana/grafana.ini
      - ../dashboard/provisioning:/etc/grafana/provisioning
      - ../dashboard/dashboards:/etc/grafana/dashboards

  nodered:
    # https://hub.docker.com/r/grafana/grafana
    # https://nodered.org/docs/getting-started/docker
    depends_on:
      - influxdb
    restart: always
    container_name: nodered
    networks:
      - lauds_gw_network
    ports:
      - 1880:1880
    environment:
      - TZ=Europe/Berlin
      - NODE_RED_ENABLE_PROJECTS=true
      - FLOWS=flows.json
    volumes:
      - nodered-data:/data
    build: ../flow
    develop:
      watch:
        - action: sync+restart
          path: ../flow/flows.json
          target: /data/flows.json

  jupyter:
    depends_on:
      - influxdb
    restart: always
    container_name: jupyter
    networks:
      - lauds_gw_network
    ports:
      - 8080:8080
      - 8050:8050
    volumes:
      - jupyter-notebook-data:/data
    build: ../jupyter
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - IF_KEY=${IF_KEY}
      - DPP_SCHEMA=${DPP_SCHEMA}
      - DPP_FQDN=${DPP_FQDN}
      - DPP_PORT=${DPP_PORT}
      - DPP_PATH=${DPP_PATH}
      - DPP_QUERY=${DPP_QUERY}

  server:
    depends_on:
      - influxdb
    restart: always
    container_name: interfacer_api
    networks:
      - lauds_gw_network
    ports:
      - 8000:8000
    volumes:
      - server-data:/data
    build: ../server

volumes:
  influxdb2:
  grafana-dashboards:
  grafana-data:
  nodered-data:
  jupyter-notebook-data:
  server-data:


networks:
  lauds_gw_network:
    #    driver: ghcr.io/devplayer0/docker-net-dhcp:release-linux-arm64-v8
    #    driver_opts:
    #      ipv6: 'true'
    #      ignore_conflicts: 'false'
    #      skip_routes: 'false'
    #    ipam:
    #      driver: 'null'
