---
- name: Clone lauds-iot-backend
  hosts: all
  tags: system
  tasks:
    - name: Updating local repository
      ansible.builtin.git:
        repo: 'https://github.com/dyne/lauds-iot-backend.git'
        dest: /home/devuan/lauds-iot-backend
        update: yes
