---
- name: Deploy SSH remote management accounts and keys
  hosts: all
  tags: operations
  tasks:
    - name: Configure sudo for sudo group
      lineinfile:
        dest: /etc/sudoers
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL)  NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Create local user account
      user:
        name: '{{ item }}'
        comment: '{{ item }}'
        shell: /usr/bin/bash
        append: yes
        groups: sudo
        generate_ssh_key: yes
        ssh_key_type: ed25519
      with_items:
        - dyne
        - adam

    - name: Add ssh public keys to users authorized_keys file
      authorized_key:
        user: '{{ item }}'
        state: present
        manage_dir: yes
        key: "{{ lookup('file', './{{ item }}.pub', errors='ignore') }}"
      with_items:
        - dyne
        - adam
